/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
/**
 *
 * @author nmare
 */
public class TelaStaffInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaStaffInicio.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaStaffInicio() {
        initComponents();
        AdmCadastro.setVisible(false);
        UserCadastro.setVisible(false);
        AddProd.setVisible(false);
        RemoverProd.setVisible(false);
        ListarProd.setVisible(false);
        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ListarProd = new javax.swing.JButton();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        Contato = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        GerenciarProdutos = new javax.swing.JButton();
        RemoverProd = new javax.swing.JButton();
        GerenciarUser = new javax.swing.JButton();
        UserCadastro = new javax.swing.JButton();
        AdmCadastro = new javax.swing.JButton();
        AddProd = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListarProd.setBackground(new java.awt.Color(102, 102, 102));
        ListarProd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ListarProd.setForeground(new java.awt.Color(255, 255, 255));
        ListarProd.setText("Editar produtos");
        ListarProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ListarProd.setContentAreaFilled(false);
        ListarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListarProd.setFocusPainted(false);
        ListarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProdActionPerformed(evt);
            }
        });
        jPanel1.add(ListarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 170, 50));

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        GerenciarProdutos.setBackground(new java.awt.Color(102, 102, 102));
        GerenciarProdutos.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        GerenciarProdutos.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarProdutos.setText("Gerenciar produtos");
        GerenciarProdutos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        GerenciarProdutos.setContentAreaFilled(false);
        GerenciarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GerenciarProdutos.setFocusPainted(false);
        GerenciarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(GerenciarProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 320, 50));

        RemoverProd.setBackground(new java.awt.Color(102, 102, 102));
        RemoverProd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        RemoverProd.setForeground(new java.awt.Color(255, 255, 255));
        RemoverProd.setText("Remover produtos");
        RemoverProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        RemoverProd.setContentAreaFilled(false);
        RemoverProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoverProd.setFocusPainted(false);
        RemoverProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverProdActionPerformed(evt);
            }
        });
        jPanel1.add(RemoverProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 170, 50));

        GerenciarUser.setBackground(new java.awt.Color(102, 102, 102));
        GerenciarUser.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        GerenciarUser.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarUser.setText("Gerenciar usuarios");
        GerenciarUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        GerenciarUser.setContentAreaFilled(false);
        GerenciarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GerenciarUser.setFocusPainted(false);
        GerenciarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarUserActionPerformed(evt);
            }
        });
        jPanel1.add(GerenciarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 320, 50));

        UserCadastro.setBackground(new java.awt.Color(102, 102, 102));
        UserCadastro.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        UserCadastro.setForeground(new java.awt.Color(255, 255, 255));
        UserCadastro.setText("Usuario cadastrados");
        UserCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        UserCadastro.setContentAreaFilled(false);
        UserCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserCadastro.setFocusPainted(false);
        UserCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(UserCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 250, 50));

        AdmCadastro.setBackground(new java.awt.Color(102, 102, 102));
        AdmCadastro.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        AdmCadastro.setForeground(new java.awt.Color(255, 255, 255));
        AdmCadastro.setText("Administradores cadastrados");
        AdmCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        AdmCadastro.setContentAreaFilled(false);
        AdmCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdmCadastro.setFocusPainted(false);
        AdmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(AdmCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 250, 50));

        AddProd.setBackground(new java.awt.Color(102, 102, 102));
        AddProd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        AddProd.setForeground(new java.awt.Color(255, 255, 255));
        AddProd.setText("Adicionar produtos");
        AddProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        AddProd.setContentAreaFilled(false);
        AddProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddProd.setFocusPainted(false);
        AddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProdActionPerformed(evt);
            }
        });
        jPanel1.add(AddProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 170, 50));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void ListarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProdActionPerformed
        // TODO add your handling code here:
        TelaStaffEditarProd screen;
        screen = new TelaStaffEditarProd();
        screen.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_ListarProdActionPerformed

    private void RemoverProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverProdActionPerformed
        // TODO add your handling code here:
        TelaStaffApagarProd screen;
        screen = new TelaStaffApagarProd();
        screen.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_RemoverProdActionPerformed

    private void GerenciarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarUserActionPerformed
        // TODO add your handling code here:
        UserCadastro.setVisible(!UserCadastro.isVisible());
        AdmCadastro.setVisible(!AdmCadastro.isVisible());
    }//GEN-LAST:event_GerenciarUserActionPerformed

    private void UserCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserCadastroActionPerformed
        // TODO add your handling code here:
        TelaStaffCadastroDeUsuario screen;
        screen = new TelaStaffCadastroDeUsuario();
        screen.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_UserCadastroActionPerformed

    private void AdmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmCadastroActionPerformed
        // TODO add your handling code here:
        TelaStaffCadastroDeStaff screen;
        screen = new TelaStaffCadastroDeStaff();
        screen.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_AdmCadastroActionPerformed

    private void GerenciarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarProdutosActionPerformed
        // TODO add your handling code here:
        AddProd.setVisible(!AddProd.isVisible());
        RemoverProd.setVisible(!RemoverProd.isVisible());
        ListarProd.setVisible(!ListarProd.isVisible());
    }//GEN-LAST:event_GerenciarProdutosActionPerformed

    private void AddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProdActionPerformed
        // TODO add your handling code here:
        TelaStaffAdicionarProd screen;
        screen = new TelaStaffAdicionarProd();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_AddProdActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaStaffInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProd;
    private javax.swing.JButton AdmCadastro;
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JButton GerenciarProdutos;
    private javax.swing.JButton GerenciarUser;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton ListarProd;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JButton RemoverProd;
    private javax.swing.JButton UserCadastro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
