/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import classe.usuario;
import classe.usuarioBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nmare
 */
public class TelaStaffCadastroDeUsuario extends javax.swing.JFrame {
    
    ArrayList<usuario> lista;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaStaffCadastroDeUsuario.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaStaffCadastroDeUsuario() {
        initComponents();
        
        usuarioBD dao = new usuarioBD();

        lista = dao.listarTodosUsuarios();

        DefaultTableModel modelo =
                (DefaultTableModel) tabelaUsuario.getModel();

        modelo.setRowCount(0);
        
        for (usuario u : lista) {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getName()
            });
        }
        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        Contato = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        DeletarUser = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Staff = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        iddoproduto = new javax.swing.JLabel();
        nomedoproduto = new javax.swing.JLabel();
        EditProd = new javax.swing.JButton();
        AtualizarUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        tipoBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        DeletarUser.setBackground(new java.awt.Color(102, 102, 102));
        DeletarUser.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        DeletarUser.setForeground(new java.awt.Color(255, 255, 255));
        DeletarUser.setText("Deletar Usuario");
        DeletarUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        DeletarUser.setContentAreaFilled(false);
        DeletarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeletarUser.setFocusPainted(false);
        DeletarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarUserActionPerformed(evt);
            }
        });
        jPanel1.add(DeletarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 320, 50));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 120, 110));

        Staff.setBackground(new java.awt.Color(102, 102, 102));
        Staff.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Staff.setForeground(new java.awt.Color(255, 255, 255));
        Staff.setText("STAFF");
        Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        jPanel1.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, -1, -1));

        password.setBackground(new java.awt.Color(102, 102, 102));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 470, 30));

        user.setBackground(new java.awt.Color(102, 102, 102));
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 470, 30));

        iddoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        iddoproduto.setForeground(new java.awt.Color(255, 255, 255));
        iddoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddoproduto.setText("Usuario:");
        jPanel1.add(iddoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 170, 40));

        nomedoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        nomedoproduto.setForeground(new java.awt.Color(255, 255, 255));
        nomedoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomedoproduto.setText("Senha:");
        jPanel1.add(nomedoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 170, 40));

        EditProd.setBackground(new java.awt.Color(102, 102, 102));
        EditProd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        EditProd.setForeground(new java.awt.Color(255, 255, 255));
        EditProd.setText("Cadastro de usuário");
        EditProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        EditProd.setContentAreaFilled(false);
        EditProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EditProd.setFocusPainted(false);
        EditProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdActionPerformed(evt);
            }
        });
        jPanel1.add(EditProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 170, 50));

        AtualizarUser.setBackground(new java.awt.Color(102, 102, 102));
        AtualizarUser.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        AtualizarUser.setForeground(new java.awt.Color(255, 255, 255));
        AtualizarUser.setText("Atualizar Usuario");
        AtualizarUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        AtualizarUser.setContentAreaFilled(false);
        AtualizarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AtualizarUser.setFocusPainted(false);
        AtualizarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarUserActionPerformed(evt);
            }
        });
        jPanel1.add(AtualizarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 320, 50));

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, -1));

        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cliente", "staff" }));
        jPanel1.add(tipoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void DeletarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarUserActionPerformed
        int linha = tabelaUsuario.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário.");
            return;
        }

        usuario item = lista.get(linha);

        usuarioBD dao = new usuarioBD();

        dao.removerUsuario(item.getId());

        JOptionPane.showMessageDialog(this, "Usuário removido!");
        
        lista = dao.listarTodosStaff();
        DefaultTableModel modelo = (DefaultTableModel) tabelaUsuario.getModel();
        modelo.setRowCount(0);

        for (usuario u : lista) {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getName()
            });
        }
    }//GEN-LAST:event_DeletarUserActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        // TODO add your handling code here:
            System.out.print("aaaa");
            TelaStaffInicio screen;
            screen = new TelaStaffInicio();
            screen.setVisible(true);

            this.setVisible(false);
    }//GEN-LAST:event_StaffActionPerformed

    private void EditProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdActionPerformed

    private void AtualizarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarUserActionPerformed
        int linha = tabelaUsuario.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um usuário.");
            return;
        }

        usuario u = lista.get(linha);

        u.setName(user.getText());
        u.setpsw(password.getText());
        u.setTipo(tipoBox.getSelectedItem().toString());

        usuarioBD dao = new usuarioBD();
        
        dao.atualizarUsuario(u);

        if (dao.atualizarUsuario(u)) {
            JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar usuário.");
        }
    }//GEN-LAST:event_AtualizarUserActionPerformed

    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked
        int linha = tabelaUsuario.getSelectedRow();

        usuario u = lista.get(linha);

        user.setText(u.getName());

        password.setText(u.getpsw());
        
        tipoBox.setSelectedItem(u.getTipo());
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaStaffCadastroDeUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarUser;
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JButton DeletarUser;
    private javax.swing.JButton EditProd;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JButton Staff;
    private javax.swing.JLabel iddoproduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomedoproduto;
    private javax.swing.JTextField password;
    private javax.swing.JTable tabelaUsuario;
    private javax.swing.JComboBox<String> tipoBox;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
