/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author nmare
 */
public class TelaStaffEditarProd extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaStaffEditarProd.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaStaffEditarProd() {
        initComponents();
        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        Contato = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Adicionarproduto = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Staff = new javax.swing.JButton();
        preco = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        descricao = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        tamanho = new javax.swing.JTextField();
        precodoproduto = new javax.swing.JLabel();
        iddoproduto = new javax.swing.JLabel();
        nomedoproduto = new javax.swing.JLabel();
        descdoproduto = new javax.swing.JLabel();
        tamanhodoproduto = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        qtddoproduto = new javax.swing.JLabel();
        GerenciarProdutos = new javax.swing.JButton();
        EditProd = new javax.swing.JButton();
        Produto1 = new javax.swing.JButton();
        Produto2 = new javax.swing.JButton();
        Produto3 = new javax.swing.JButton();
        Produto4 = new javax.swing.JButton();
        Produto5 = new javax.swing.JButton();
        Produto6 = new javax.swing.JButton();
        Produto7 = new javax.swing.JButton();
        Produto8 = new javax.swing.JButton();
        Produto9 = new javax.swing.JButton();
        Produto10 = new javax.swing.JButton();
        Produto11 = new javax.swing.JButton();
        Produto12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Adicionarproduto.setBackground(new java.awt.Color(102, 102, 102));
        Adicionarproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Adicionarproduto.setForeground(new java.awt.Color(255, 255, 255));
        Adicionarproduto.setText("Atualizar produto");
        Adicionarproduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Adicionarproduto.setContentAreaFilled(false);
        Adicionarproduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Adicionarproduto.setFocusPainted(false);
        Adicionarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarprodutoActionPerformed(evt);
            }
        });
        jPanel1.add(Adicionarproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 320, 50));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        Staff.setBackground(new java.awt.Color(102, 102, 102));
        Staff.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Staff.setForeground(new java.awt.Color(255, 255, 255));
        Staff.setText("STAFF");
        Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        jPanel1.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, -1, -1));

        preco.setBackground(new java.awt.Color(102, 102, 102));
        preco.setForeground(new java.awt.Color(255, 255, 255));
        preco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 470, 30));

        nome.setBackground(new java.awt.Color(102, 102, 102));
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 470, 30));

        descricao.setBackground(new java.awt.Color(102, 102, 102));
        descricao.setForeground(new java.awt.Color(255, 255, 255));
        descricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 470, 30));

        id.setBackground(new java.awt.Color(102, 102, 102));
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 470, 30));

        tamanho.setBackground(new java.awt.Color(102, 102, 102));
        tamanho.setForeground(new java.awt.Color(255, 255, 255));
        tamanho.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(tamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 470, 30));

        precodoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        precodoproduto.setForeground(new java.awt.Color(255, 255, 255));
        precodoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precodoproduto.setText("Preço do produto:");
        jPanel1.add(precodoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 170, 40));

        iddoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        iddoproduto.setForeground(new java.awt.Color(255, 255, 255));
        iddoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddoproduto.setText("ID do produto:");
        jPanel1.add(iddoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 170, 40));

        nomedoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        nomedoproduto.setForeground(new java.awt.Color(255, 255, 255));
        nomedoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomedoproduto.setText("Nome do produto:");
        jPanel1.add(nomedoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 170, 40));

        descdoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        descdoproduto.setForeground(new java.awt.Color(255, 255, 255));
        descdoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descdoproduto.setText("Descrição do produto:");
        jPanel1.add(descdoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 170, 40));

        tamanhodoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        tamanhodoproduto.setForeground(new java.awt.Color(255, 255, 255));
        tamanhodoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanhodoproduto.setText("Tamanho do produto:");
        jPanel1.add(tamanhodoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 170, 40));

        quantidade.setBackground(new java.awt.Color(102, 102, 102));
        quantidade.setForeground(new java.awt.Color(255, 255, 255));
        quantidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 470, 30));

        qtddoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        qtddoproduto.setForeground(new java.awt.Color(255, 255, 255));
        qtddoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtddoproduto.setText("Quantidade do produto:");
        jPanel1.add(qtddoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 170, 40));

        GerenciarProdutos.setBackground(new java.awt.Color(102, 102, 102));
        GerenciarProdutos.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        GerenciarProdutos.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarProdutos.setText("Gerenciar produtos");
        GerenciarProdutos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        GerenciarProdutos.setContentAreaFilled(false);
        GerenciarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GerenciarProdutos.setFocusPainted(false);
        GerenciarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(GerenciarProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 320, 50));

        EditProd.setBackground(new java.awt.Color(102, 102, 102));
        EditProd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        EditProd.setForeground(new java.awt.Color(255, 255, 255));
        EditProd.setText("Editar produtos");
        EditProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        EditProd.setContentAreaFilled(false);
        EditProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EditProd.setFocusPainted(false);
        EditProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdActionPerformed(evt);
            }
        });
        jPanel1.add(EditProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 50));

        Produto1.setBackground(new java.awt.Color(102, 102, 102));
        Produto1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto1.setForeground(new java.awt.Color(255, 255, 255));
        Produto1.setText("Off-White Camiseta Arrow");
        Produto1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto1.setContentAreaFilled(false);
        Produto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto1.setFocusPainted(false);
        Produto1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto1ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 240, 30));

        Produto2.setBackground(new java.awt.Color(102, 102, 102));
        Produto2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto2.setForeground(new java.awt.Color(255, 255, 255));
        Produto2.setText("adidas Camiseta Mercedes-AMG Formula 1 Team");
        Produto2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto2.setContentAreaFilled(false);
        Produto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto2.setFocusPainted(false);
        Produto2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto2ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 240, 30));

        Produto3.setBackground(new java.awt.Color(102, 102, 102));
        Produto3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto3.setForeground(new java.awt.Color(255, 255, 255));
        Produto3.setText("Off-White Camiseta com estampa de logo");
        Produto3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto3.setContentAreaFilled(false);
        Produto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto3.setFocusPainted(false);
        Produto3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto3ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 240, 30));

        Produto4.setBackground(new java.awt.Color(102, 102, 102));
        Produto4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto4.setForeground(new java.awt.Color(255, 255, 255));
        Produto4.setText("Nike Tênis x Supreme Air Force 1 Low");
        Produto4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto4.setContentAreaFilled(false);
        Produto4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto4.setFocusPainted(false);
        Produto4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto4ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 240, 30));

        Produto5.setBackground(new java.awt.Color(102, 102, 102));
        Produto5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto5.setForeground(new java.awt.Color(255, 255, 255));
        Produto5.setText("Jordan Tênis Air Jordan 1 High OG SP Travis Scott");
        Produto5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto5.setContentAreaFilled(false);
        Produto5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto5.setFocusPainted(false);
        Produto5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto5ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 240, 30));

        Produto6.setBackground(new java.awt.Color(102, 102, 102));
        Produto6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto6.setForeground(new java.awt.Color(255, 255, 255));
        Produto6.setText("Nike Tênis  Travis Scott Air Force 1 Low 'Cactus Jack'");
        Produto6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto6.setContentAreaFilled(false);
        Produto6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto6.setFocusPainted(false);
        Produto6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto6ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 240, 30));

        Produto7.setBackground(new java.awt.Color(102, 102, 102));
        Produto7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto7.setForeground(new java.awt.Color(255, 255, 255));
        Produto7.setText("VETEMENTS Bermuda cargo jeans cintura alta  ");
        Produto7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto7.setContentAreaFilled(false);
        Produto7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto7.setFocusPainted(false);
        Produto7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto7ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 240, 30));

        Produto8.setBackground(new java.awt.Color(102, 102, 102));
        Produto8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto8.setForeground(new java.awt.Color(255, 255, 255));
        Produto8.setText("Helmut Lang Bermuda de couro");
        Produto8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto8.setContentAreaFilled(false);
        Produto8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto8.setFocusPainted(false);
        Produto8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto8ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, 30));

        Produto9.setBackground(new java.awt.Color(102, 102, 102));
        Produto9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto9.setForeground(new java.awt.Color(255, 255, 255));
        Produto9.setText("Dolce & Gabbana Short com estampa de logo");
        Produto9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto9.setContentAreaFilled(false);
        Produto9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto9.setFocusPainted(false);
        Produto9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto9ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 240, 30));

        Produto10.setBackground(new java.awt.Color(102, 102, 102));
        Produto10.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto10.setForeground(new java.awt.Color(255, 255, 255));
        Produto10.setText("Manière De Voir Calça wide leg Serge com pregas");
        Produto10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto10.setContentAreaFilled(false);
        Produto10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto10.setFocusPainted(false);
        Produto10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto10ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 240, 30));

        Produto11.setBackground(new java.awt.Color(102, 102, 102));
        Produto11.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto11.setForeground(new java.awt.Color(255, 255, 255));
        Produto11.setText("Palm Angels Calça esportiva com listra");
        Produto11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto11.setContentAreaFilled(false);
        Produto11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto11.setFocusPainted(false);
        Produto11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto11ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 240, 30));

        Produto12.setBackground(new java.awt.Color(102, 102, 102));
        Produto12.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Produto12.setForeground(new java.awt.Color(255, 255, 255));
        Produto12.setText("GCDS Calça cargo wide leg de tweed");
        Produto12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Produto12.setContentAreaFilled(false);
        Produto12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produto12.setFocusPainted(false);
        Produto12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Produto12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produto12ActionPerformed(evt);
            }
        });
        jPanel1.add(Produto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void AdicionarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarprodutoActionPerformed

    // id
    if (id.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo ID é obrigatório!");
        id.requestFocus();
        return;
    }
    
    // nome
    if (nome.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo Nome é obrigatório!");
        nome.requestFocus();
        return;
    }
    
    // descrição
    if (descricao.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo Descrição é obrigatório!");
        descricao.requestFocus();
        return;
    }
    
    // tamanho
    if (tamanho.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo Tamanho é obrigatório!");
        tamanho.requestFocus();
        return;
    }
    
    // preco
    if (preco.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo Preço é obrigatório!");
        preco.requestFocus();
        return;
    }
    
    // quantidade
    if (quantidade.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "O campo Quantidade é obrigatório!");
        quantidade.requestFocus();
        return;
    }
    
    JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!");
    }//GEN-LAST:event_AdicionarprodutoActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        // TODO add your handling code here:
            System.out.print("aaaa");
            TelaStaffInicio screen;
            screen = new TelaStaffInicio();
            screen.setVisible(true);

            this.setVisible(false);
    }//GEN-LAST:event_StaffActionPerformed

    private void GerenciarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GerenciarProdutosActionPerformed

    private void EditProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProdActionPerformed

    private void Produto12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto12ActionPerformed

        id.setText("0009");
        nome.setText("GCDS");
        descricao.setText("Calça cargo wide leg de tweed");
        tamanho.setText("38, 40");
        preco.setText("R$ 7.100,00");
        quantidade.setText("2");
    }//GEN-LAST:event_Produto12ActionPerformed

    private void Produto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto1ActionPerformed

        id.setText("0011");
        nome.setText("Off-White");
        descricao.setText("Camiseta Arrow");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 2.497,00");
        quantidade.setText("8");
    }//GEN-LAST:event_Produto1ActionPerformed

    private void Produto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto2ActionPerformed
        // TODO add your handling code here:
        id.setText("0010");
        nome.setText("adidas");
        descricao.setText("Camiseta Mercedes-AMG Formula 1 Team");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 1.291,00");
        quantidade.setText("6");
    }//GEN-LAST:event_Produto2ActionPerformed

    private void Produto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto3ActionPerformed

        id.setText("0012");
        nome.setText("Off-White");
        descricao.setText("Camiseta com estampa de logo");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 2.620,00");
        quantidade.setText("13");
    }//GEN-LAST:event_Produto3ActionPerformed

    private void Produto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto4ActionPerformed

        id.setText("0006");
        nome.setText("Nike");
        descricao.setText("Tênis x Supreme Air Force 1 Low");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 2.574,00");
        quantidade.setText("6");
    }//GEN-LAST:event_Produto4ActionPerformed

    private void Produto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto5ActionPerformed

        id.setText("0005");
        nome.setText("Jordan");
        descricao.setText("Tênis Air Jordan 1 High OG SP Travis Scott");
        tamanho.setText("40, 42");
        preco.setText("R$ 27.402,00");
        quantidade.setText("6");
    }//GEN-LAST:event_Produto5ActionPerformed

    private void Produto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto6ActionPerformed

        id.setText("0004");
        nome.setText("Nike");
        descricao.setText("Tênis Travis Scott Air Force 1 Low 'Cactus Jack'");
        tamanho.setText("36, 38");
        preco.setText("R$ 11.330,00");
        quantidade.setText("2");
    }//GEN-LAST:event_Produto6ActionPerformed

    private void Produto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto7ActionPerformed

        id.setText("0005");
        nome.setText("VETEMENTS");
        descricao.setText("Bermuda cargo jeans cintura alta");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 16.153,00");
        quantidade.setText("6");
    }//GEN-LAST:event_Produto7ActionPerformed

    private void Produto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto8ActionPerformed

        id.setText("0002");
        nome.setText("Helmut Lang");
        descricao.setText("Bermuda de couro");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 7.933,00");
        quantidade.setText("8");
    }//GEN-LAST:event_Produto8ActionPerformed

    private void Produto9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto9ActionPerformed

        id.setText("0003");
        nome.setText("Dolce & Gabbana");
        descricao.setText("Short com estampa de logo");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 11.276,00");
        quantidade.setText("4");
    }//GEN-LAST:event_Produto9ActionPerformed

    private void Produto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto10ActionPerformed

        id.setText("0007");
        nome.setText("Manière De Voir");
        descricao.setText("Calça wide leg Serge com pregas");
        tamanho.setText("36, 38");
        preco.setText("R$ 2.354,00");
        quantidade.setText("2");
    }//GEN-LAST:event_Produto10ActionPerformed

    private void Produto11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produto11ActionPerformed

        id.setText("0008");
        nome.setText("Palm Angels");
        descricao.setText("Calça esportiva com listra");
        tamanho.setText("36, 38, 40, 42");
        preco.setText("R$ 4.392,00");
        quantidade.setText("4");
    }//GEN-LAST:event_Produto11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaStaffEditarProd().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionarproduto;
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JButton EditProd;
    private javax.swing.JButton GerenciarProdutos;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JButton Produto1;
    private javax.swing.JButton Produto10;
    private javax.swing.JButton Produto11;
    private javax.swing.JButton Produto12;
    private javax.swing.JButton Produto2;
    private javax.swing.JButton Produto3;
    private javax.swing.JButton Produto4;
    private javax.swing.JButton Produto5;
    private javax.swing.JButton Produto6;
    private javax.swing.JButton Produto7;
    private javax.swing.JButton Produto8;
    private javax.swing.JButton Produto9;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JButton Staff;
    private javax.swing.JLabel descdoproduto;
    private javax.swing.JTextField descricao;
    private javax.swing.JTextField id;
    private javax.swing.JLabel iddoproduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomedoproduto;
    private javax.swing.JTextField preco;
    private javax.swing.JLabel precodoproduto;
    private javax.swing.JLabel qtddoproduto;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField tamanho;
    private javax.swing.JLabel tamanhodoproduto;
    // End of variables declaration//GEN-END:variables
}
