/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import classe.produto;
import classe.produtoBD;
import classe.carrinho;
import classe.carrinhoBD;
import classe.Sessao;
import javax.swing.JOptionPane;

/**
 *
 * @author nmare
 */
public class TelaCalcados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCalcados.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaCalcados() {
        initComponents();

        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TITULO5 = new javax.swing.JLabel();
        Carrinho3 = new javax.swing.JButton();
        Carrinho2 = new javax.swing.JButton();
        Carrinho1 = new javax.swing.JButton();
        TITULO6 = new javax.swing.JLabel();
        TITULO4 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Contato = new javax.swing.JButton();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        IdProduto3 = new javax.swing.JLabel();
        IdProduto2 = new javax.swing.JLabel();
        IdProduto1 = new javax.swing.JLabel();
        Tamanho1 = new javax.swing.JLabel();
        Size1 = new javax.swing.JComboBox<>();
        Tamanho2 = new javax.swing.JLabel();
        Size2 = new javax.swing.JComboBox<>();
        Tamanho3 = new javax.swing.JLabel();
        Size3 = new javax.swing.JComboBox<>();
        QUANTITDADE = new javax.swing.JLabel();
        Produtos2 = new javax.swing.JComboBox<>();
        QUANTITDADE1 = new javax.swing.JLabel();
        Produtos3 = new javax.swing.JComboBox<>();
        QUANTITDADE2 = new javax.swing.JLabel();
        Produtos4 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("12 x R$214,50");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 90, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("R$ 2.574");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 90, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jordan Tênis Air Jordan 1 High OG SP Travis Scott");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 320, 37));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("12 x R$2.283,50");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R$ 11.330,00");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("R$ 27.402,00");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 90, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nike Tênis  Travis Scott Air Force 1 Low 'Cactus Jack'");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("12 x R$944,17");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nike Tênis x Supreme Air Force 1 Low");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 320, 37));

        TITULO5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO5.setForeground(new java.awt.Color(255, 255, 255));
        TITULO5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTOairsupreme.png"))); // NOI18N
        TITULO5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 265, -1, 270));

        Carrinho3.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Carrinho3.setForeground(new java.awt.Color(255, 255, 255));
        Carrinho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho3.setText("Compre agora");
        Carrinho3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrinho3ActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 167, 61));

        Carrinho2.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Carrinho2.setForeground(new java.awt.Color(255, 255, 255));
        Carrinho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho2.setText("Compre agora");
        Carrinho2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrinho2ActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 167, 61));

        Carrinho1.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Carrinho1.setForeground(new java.awt.Color(255, 255, 255));
        Carrinho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho1.setText("Compre agora");
        Carrinho1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrinho1ActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 167, 61));

        TITULO6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO6.setForeground(new java.awt.Color(255, 255, 255));
        TITULO6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTOtravisair.png"))); // NOI18N
        TITULO6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 265, -1, 270));

        TITULO4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO4.setForeground(new java.awt.Color(255, 255, 255));
        TITULO4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTOjordantravis.png"))); // NOI18N
        TITULO4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 265, -1, -1));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        IdProduto3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        IdProduto3.setForeground(new java.awt.Color(255, 255, 255));
        IdProduto3.setText("Id: 0006");
        IdProduto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IdProduto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 60, 20));

        IdProduto2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        IdProduto2.setForeground(new java.awt.Color(255, 255, 255));
        IdProduto2.setText("Id: 0005");
        IdProduto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IdProduto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 60, 20));

        IdProduto1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        IdProduto1.setForeground(new java.awt.Color(255, 255, 255));
        IdProduto1.setText("Id: 0004");
        IdProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IdProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 60, 20));

        Tamanho1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Tamanho1.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho1.setText("Tamanho:");
        Tamanho1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Tamanho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 70, 20));

        Size1.setBackground(new java.awt.Color(102, 102, 102));
        Size1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Size1.setForeground(new java.awt.Color(255, 255, 255));
        Size1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "36", "38" }));
        Size1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Size1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size1ActionPerformed(evt);
            }
        });
        jPanel1.add(Size1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 50, 20));

        Tamanho2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Tamanho2.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho2.setText("Tamanho:");
        Tamanho2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Tamanho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 70, 20));

        Size2.setBackground(new java.awt.Color(102, 102, 102));
        Size2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Size2.setForeground(new java.awt.Color(255, 255, 255));
        Size2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40", "42" }));
        Size2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Size2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size2ActionPerformed(evt);
            }
        });
        jPanel1.add(Size2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 50, 20));

        Tamanho3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Tamanho3.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho3.setText("Tamanho:");
        Tamanho3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Tamanho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 70, 20));

        Size3.setBackground(new java.awt.Color(102, 102, 102));
        Size3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Size3.setForeground(new java.awt.Color(255, 255, 255));
        Size3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "36", "38", "40", "42" }));
        Size3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Size3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size3ActionPerformed(evt);
            }
        });
        jPanel1.add(Size3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 50, 20));

        QUANTITDADE.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        QUANTITDADE.setForeground(new java.awt.Color(255, 255, 255));
        QUANTITDADE.setText("Quantidade:");
        jPanel1.add(QUANTITDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 80, -1));

        Produtos2.setBackground(new java.awt.Color(102, 102, 102));
        Produtos2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos2.setForeground(new java.awt.Color(255, 255, 255));
        Produtos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "0" }));
        Produtos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos2ActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 680, 50, 20));

        QUANTITDADE1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        QUANTITDADE1.setForeground(new java.awt.Color(255, 255, 255));
        QUANTITDADE1.setText("Quantidade:");
        jPanel1.add(QUANTITDADE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 80, -1));

        Produtos3.setBackground(new java.awt.Color(102, 102, 102));
        Produtos3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos3.setForeground(new java.awt.Color(255, 255, 255));
        Produtos3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "0" }));
        Produtos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos3ActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 680, 50, 20));

        QUANTITDADE2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        QUANTITDADE2.setForeground(new java.awt.Color(255, 255, 255));
        QUANTITDADE2.setText("Quantidade:");
        jPanel1.add(QUANTITDADE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 80, -1));

        Produtos4.setBackground(new java.awt.Color(102, 102, 102));
        Produtos4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos4.setForeground(new java.awt.Color(255, 255, 255));
        Produtos4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "0" }));
        Produtos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos4ActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carrinho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrinho3ActionPerformed
        // TODO add your handling code here:
        int tamanho = Integer.parseInt(Size3.getSelectedItem().toString());
        int quantidade = Integer.parseInt(Produtos3.getSelectedItem().toString());
        String nomeProduto = "Nike Tênis x Supreme Air Force 1 Low";

        produtoBD produtoBD = new classe.produtoBD();
        produto produtoEncontrado = produtoBD.buscarPorNomeETamanho(nomeProduto, tamanho);

        if (produtoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Produto/tamanho não encontrado.");
            return;
        }

        if (quantidade > produtoEncontrado.getEstoque()) {
            JOptionPane.showMessageDialog(this, "Quantidade indisponível em estoque.");
            return;
        }

        int idUsuarioLogado = Sessao.getUsuarioLogado().getId(); // ver observação abaixo

        carrinhoBD carrinhoBD = new classe.carrinhoBD();
        boolean sucesso = carrinhoBD.adicionarItem(idUsuarioLogado, produtoEncontrado.getId(), quantidade);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ao carrinho.");
            return;
        }

        System.out.println("ID Produto: " + produtoEncontrado.getId());
        System.out.println("Tamanho: " + tamanho);
        System.out.println("Quantidade: " + quantidade);

        TelaCarrinho screen = new TelaCarrinho();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Carrinho3ActionPerformed

    private void Carrinho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrinho2ActionPerformed
        // TODO add your handling code here:
        int tamanho = Integer.parseInt(Size2.getSelectedItem().toString());
        int quantidade = Integer.parseInt(Produtos2.getSelectedItem().toString());
        String nomeProduto = "Jordan Air Jordan 1 High OG SP Travis Scott";

        produtoBD produtoBD = new classe.produtoBD();
        produto produtoEncontrado = produtoBD.buscarPorNomeETamanho(nomeProduto, tamanho);

        if (produtoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Produto/tamanho não encontrado.");
            return;
        }

        if (quantidade > produtoEncontrado.getEstoque()) {
            JOptionPane.showMessageDialog(this, "Quantidade indisponível em estoque.");
            return;
        }

        int idUsuarioLogado = Sessao.getUsuarioLogado().getId(); // ver observação abaixo

        carrinhoBD carrinhoBD = new classe.carrinhoBD();
        boolean sucesso = carrinhoBD.adicionarItem(idUsuarioLogado, produtoEncontrado.getId(), quantidade);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ao carrinho.");
            return;
        }

        System.out.println("ID Produto: " + produtoEncontrado.getId());
        System.out.println("Tamanho: " + tamanho);
        System.out.println("Quantidade: " + quantidade);

        TelaCarrinho screen = new TelaCarrinho();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Carrinho2ActionPerformed

    private void Carrinho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrinho1ActionPerformed
        int tamanho = Integer.parseInt(Size1.getSelectedItem().toString());
        int quantidade = Integer.parseInt(Produtos4.getSelectedItem().toString());
        String nomeProduto = "Nike Tênis  Travis Scott Air Force 1 Low 'Cactus Jack'";

        produtoBD produtoBD = new classe.produtoBD();
        produto produtoEncontrado = produtoBD.buscarPorNomeETamanho(nomeProduto, tamanho);

        if (produtoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Produto/tamanho não encontrado.");
            return;
        }

        if (quantidade > produtoEncontrado.getEstoque()) {
            JOptionPane.showMessageDialog(this, "Quantidade indisponível em estoque.");
            return;
        }

        int idUsuarioLogado = Sessao.getUsuarioLogado().getId(); // ver observação abaixo

        carrinhoBD carrinhoBD = new classe.carrinhoBD();
        boolean sucesso = carrinhoBD.adicionarItem(idUsuarioLogado, produtoEncontrado.getId(), quantidade);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ao carrinho.");
            return;
        }

        System.out.println("ID Produto: " + produtoEncontrado.getId());
        System.out.println("Tamanho: " + tamanho);
        System.out.println("Quantidade: " + quantidade);

        TelaCarrinho screen = new TelaCarrinho();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Carrinho1ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void Size1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size1ActionPerformed

    private void Size2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size2ActionPerformed

    private void Size3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size3ActionPerformed

    private void Produtos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos2ActionPerformed

    private void Produtos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos3ActionPerformed

    private void Produtos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCalcados().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Carrinho1;
    private javax.swing.JButton Carrinho2;
    private javax.swing.JButton Carrinho3;
    private javax.swing.JButton Contato;
    private javax.swing.JButton Home;
    private javax.swing.JLabel IdProduto1;
    private javax.swing.JLabel IdProduto2;
    private javax.swing.JLabel IdProduto3;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JComboBox<String> Produtos2;
    private javax.swing.JComboBox<String> Produtos3;
    private javax.swing.JComboBox<String> Produtos4;
    private javax.swing.JLabel QUANTITDADE;
    private javax.swing.JLabel QUANTITDADE1;
    private javax.swing.JLabel QUANTITDADE2;
    private javax.swing.JComboBox<String> Size1;
    private javax.swing.JComboBox<String> Size2;
    private javax.swing.JComboBox<String> Size3;
    private javax.swing.JLabel TITULO4;
    private javax.swing.JLabel TITULO5;
    private javax.swing.JLabel TITULO6;
    private javax.swing.JLabel Tamanho1;
    private javax.swing.JLabel Tamanho2;
    private javax.swing.JLabel Tamanho3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
