/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import classe.Sessao;
import classe.carrinhoBD;
import classe.produto;
import classe.produtoBD;
import javax.swing.JOptionPane;

/**
 *
 * @author nmare
 */
public class TelaCalcas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCalcas.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaCalcas() {
        initComponents();

        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TITULO1 = new javax.swing.JLabel();
        TITULO2 = new javax.swing.JLabel();
        TITULO3 = new javax.swing.JLabel();
        PARCELA3 = new javax.swing.JLabel();
        PRECO3 = new javax.swing.JLabel();
        PARCELA2 = new javax.swing.JLabel();
        PRECO2 = new javax.swing.JLabel();
        PARCELA1 = new javax.swing.JLabel();
        PRECO1 = new javax.swing.JLabel();
        Carrinho10 = new javax.swing.JButton();
        Carrinho13 = new javax.swing.JButton();
        Carrinho14 = new javax.swing.JButton();
        TITULO4 = new javax.swing.JLabel();
        TITULO5 = new javax.swing.JLabel();
        TITULO6 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Contato = new javax.swing.JButton();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        IdProduto3 = new javax.swing.JLabel();
        IdProduto2 = new javax.swing.JLabel();
        IdProduto1 = new javax.swing.JLabel();
        Tamanho1 = new javax.swing.JLabel();
        Size1 = new javax.swing.JComboBox<>();
        Tamanho2 = new javax.swing.JLabel();
        Size2 = new javax.swing.JComboBox<>();
        Tamanho3 = new javax.swing.JLabel();
        Size3 = new javax.swing.JComboBox<>();
        QUANTITDADE2 = new javax.swing.JLabel();
        Produtos7 = new javax.swing.JComboBox<>();
        QUANTITDADE = new javax.swing.JLabel();
        Produtos2 = new javax.swing.JComboBox<>();
        QUANTITDADE1 = new javax.swing.JLabel();
        Produtos3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO1.setForeground(new java.awt.Color(255, 255, 255));
        TITULO1.setText("Manière De Voir Calça wide leg Serge com pregas");
        TITULO1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 557, 320, 30));

        TITULO2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO2.setForeground(new java.awt.Color(255, 255, 255));
        TITULO2.setText("Palm Angels Calça esportiva com listra");
        TITULO2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TITULO2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(TITULO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, 37));

        TITULO3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO3.setForeground(new java.awt.Color(255, 255, 255));
        TITULO3.setText("GCDS Calça cargo wide leg de tweed");
        TITULO3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 240, 37));

        PARCELA3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PARCELA3.setForeground(new java.awt.Color(255, 255, 255));
        PARCELA3.setText("12 x R$534,17");
        jPanel1.add(PARCELA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 90, -1));

        PRECO3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PRECO3.setForeground(new java.awt.Color(255, 255, 255));
        PRECO3.setText("R$ 8.013,00");
        jPanel1.add(PRECO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 90, -1));

        PARCELA2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PARCELA2.setForeground(new java.awt.Color(255, 255, 255));
        PARCELA2.setText("12 x R$292,75");
        jPanel1.add(PARCELA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 90, -1));

        PRECO2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PRECO2.setForeground(new java.awt.Color(255, 255, 255));
        PRECO2.setText("R$ 4.392,00");
        jPanel1.add(PRECO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 90, -1));

        PARCELA1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PARCELA1.setForeground(new java.awt.Color(255, 255, 255));
        PARCELA1.setText("12 x R$196,17");
        jPanel1.add(PARCELA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, 20));

        PRECO1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PRECO1.setForeground(new java.awt.Color(255, 255, 255));
        PRECO1.setText("R$ 2.354,00");
        jPanel1.add(PRECO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 90, 20));

        Carrinho10.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Carrinho10.setForeground(new java.awt.Color(255, 255, 255));
        Carrinho10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho10.setText("Compre agora");
        Carrinho10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrinho10ActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 591, 167, 60));

        Carrinho13.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho13.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Carrinho13.setForeground(new java.awt.Color(255, 255, 255));
        Carrinho13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho13.setText("Compre agora");
        Carrinho13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrinho13ActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 167, 61));

        Carrinho14.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho14.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Carrinho14.setForeground(new java.awt.Color(255, 255, 255));
        Carrinho14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho14.setText("Compre agora");
        Carrinho14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrinho14ActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 167, 61));

        TITULO4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO4.setForeground(new java.awt.Color(255, 255, 255));
        TITULO4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTOPALM.png"))); // NOI18N
        TITULO4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 265, -1, -1));

        TITULO5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO5.setForeground(new java.awt.Color(255, 255, 255));
        TITULO5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTOGC.png"))); // NOI18N
        TITULO5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 265, -1, 270));

        TITULO6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        TITULO6.setForeground(new java.awt.Color(255, 255, 255));
        TITULO6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTOvoir.png"))); // NOI18N
        TITULO6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(TITULO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 270));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        IdProduto3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        IdProduto3.setForeground(new java.awt.Color(255, 255, 255));
        IdProduto3.setText("Id: 0009");
        IdProduto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IdProduto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 60, 20));

        IdProduto2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        IdProduto2.setForeground(new java.awt.Color(255, 255, 255));
        IdProduto2.setText("Id: 0008");
        IdProduto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IdProduto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 60, 20));

        IdProduto1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        IdProduto1.setForeground(new java.awt.Color(255, 255, 255));
        IdProduto1.setText("Id: 0007");
        IdProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IdProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 60, 20));

        Tamanho1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Tamanho1.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho1.setText("Tamanho:");
        Tamanho1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Tamanho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 70, 20));

        Size1.setBackground(new java.awt.Color(102, 102, 102));
        Size1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Size1.setForeground(new java.awt.Color(255, 255, 255));
        Size1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "36", "38" }));
        Size1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Size1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size1ActionPerformed(evt);
            }
        });
        jPanel1.add(Size1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 50, 20));

        Tamanho2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Tamanho2.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho2.setText("Tamanho:");
        Tamanho2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Tamanho2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 70, 20));

        Size2.setBackground(new java.awt.Color(102, 102, 102));
        Size2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Size2.setForeground(new java.awt.Color(255, 255, 255));
        Size2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "36", "38", "40", "42" }));
        Size2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Size2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size2ActionPerformed(evt);
            }
        });
        jPanel1.add(Size2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 50, 20));

        Tamanho3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Tamanho3.setForeground(new java.awt.Color(255, 255, 255));
        Tamanho3.setText("Tamanho:");
        Tamanho3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Tamanho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 70, 20));

        Size3.setBackground(new java.awt.Color(102, 102, 102));
        Size3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Size3.setForeground(new java.awt.Color(255, 255, 255));
        Size3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "38", "40" }));
        Size3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Size3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size3ActionPerformed(evt);
            }
        });
        jPanel1.add(Size3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 50, 20));

        QUANTITDADE2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        QUANTITDADE2.setForeground(new java.awt.Color(255, 255, 255));
        QUANTITDADE2.setText("Quantidade:");
        jPanel1.add(QUANTITDADE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 80, -1));

        Produtos7.setBackground(new java.awt.Color(102, 102, 102));
        Produtos7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos7.setForeground(new java.awt.Color(255, 255, 255));
        Produtos7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        Produtos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos7ActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 50, 20));

        QUANTITDADE.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        QUANTITDADE.setForeground(new java.awt.Color(255, 255, 255));
        QUANTITDADE.setText("Quantidade:");
        jPanel1.add(QUANTITDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, 80, -1));

        Produtos2.setBackground(new java.awt.Color(102, 102, 102));
        Produtos2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos2.setForeground(new java.awt.Color(255, 255, 255));
        Produtos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        Produtos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos2ActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 680, 50, 20));

        QUANTITDADE1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        QUANTITDADE1.setForeground(new java.awt.Color(255, 255, 255));
        QUANTITDADE1.setText("Quantidade:");
        jPanel1.add(QUANTITDADE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 680, 80, -1));

        Produtos3.setBackground(new java.awt.Color(102, 102, 102));
        Produtos3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos3.setForeground(new java.awt.Color(255, 255, 255));
        Produtos3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        Produtos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produtos3ActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 680, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carrinho14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrinho14ActionPerformed
        int tamanho = Integer.parseInt(Size3.getSelectedItem().toString());
        int quantidade = Integer.parseInt(Produtos3.getSelectedItem().toString());
        String nomeProduto = "GCDS Calça cargo wide leg de tweed";

        produtoBD produtoBD = new classe.produtoBD();
        produto produtoEncontrado = produtoBD.buscarPorNomeETamanho(nomeProduto, tamanho);

        if (produtoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Produto/tamanho não encontrado.");
            return;
        }

        if (quantidade > produtoEncontrado.getEstoque()) {
            JOptionPane.showMessageDialog(this, "Quantidade indisponível em estoque.");
            return;
        }

        int idUsuarioLogado = Sessao.getUsuarioLogado().getId(); // ver observação abaixo

        carrinhoBD carrinhoBD = new classe.carrinhoBD();
        boolean sucesso = carrinhoBD.adicionarItem(idUsuarioLogado, produtoEncontrado.getId(), quantidade);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ao carrinho.");
            return;
        }

        System.out.println("ID Produto: " + produtoEncontrado.getId());
        System.out.println("Tamanho: " + tamanho);
        System.out.println("Quantidade: " + quantidade);

        TelaCarrinho screen = new TelaCarrinho();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Carrinho14ActionPerformed

    private void Carrinho13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrinho13ActionPerformed
        int tamanho = Integer.parseInt(Size2.getSelectedItem().toString());
        int quantidade = Integer.parseInt(Produtos2.getSelectedItem().toString());
        String nomeProduto = "Palm Angels Calça esportiva com listra";

        produtoBD produtoBD = new classe.produtoBD();
        produto produtoEncontrado = produtoBD.buscarPorNomeETamanho(nomeProduto, tamanho);

        if (produtoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Produto/tamanho não encontrado.");
            return;
        }

        if (quantidade > produtoEncontrado.getEstoque()) {
            JOptionPane.showMessageDialog(this, "Quantidade indisponível em estoque.");
            return;
        }

        int idUsuarioLogado = Sessao.getUsuarioLogado().getId(); // ver observação abaixo

        carrinhoBD carrinhoBD = new classe.carrinhoBD();
        boolean sucesso = carrinhoBD.adicionarItem(idUsuarioLogado, produtoEncontrado.getId(), quantidade);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ao carrinho.");
            return;
        }

        System.out.println("ID Produto: " + produtoEncontrado.getId());
        System.out.println("Tamanho: " + tamanho);
        System.out.println("Quantidade: " + quantidade);

        TelaCarrinho screen = new TelaCarrinho();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Carrinho13ActionPerformed

    private void Carrinho10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrinho10ActionPerformed
        int tamanho = Integer.parseInt(Size1.getSelectedItem().toString());
        int quantidade = Integer.parseInt(Produtos7.getSelectedItem().toString());
        String nomeProduto = "Manière De Voir Calça wide leg Serge com pregas";

        produtoBD produtoBD = new classe.produtoBD();
        produto produtoEncontrado = produtoBD.buscarPorNomeETamanho(nomeProduto, tamanho);

        if (produtoEncontrado == null) {
            JOptionPane.showMessageDialog(this, "Produto/tamanho não encontrado.");
            return;
        }

        if (quantidade > produtoEncontrado.getEstoque()) {
            JOptionPane.showMessageDialog(this, "Quantidade indisponível em estoque.");
            return;
        }

        int idUsuarioLogado = Sessao.getUsuarioLogado().getId(); // ver observação abaixo

        carrinhoBD carrinhoBD = new classe.carrinhoBD();
        boolean sucesso = carrinhoBD.adicionarItem(idUsuarioLogado, produtoEncontrado.getId(), quantidade);

        if (!sucesso) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ao carrinho.");
            return;
        }

        System.out.println("ID Produto: " + produtoEncontrado.getId());
        System.out.println("Tamanho: " + tamanho);
        System.out.println("Quantidade: " + quantidade);

        TelaCarrinho screen = new TelaCarrinho();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Carrinho10ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void Size1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size1ActionPerformed

    private void Size2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size2ActionPerformed

    private void Size3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size3ActionPerformed

    private void Produtos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos7ActionPerformed

    private void Produtos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos2ActionPerformed

    private void Produtos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produtos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Produtos3ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new TelaCalcas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Carrinho10;
    private javax.swing.JButton Carrinho13;
    private javax.swing.JButton Carrinho14;
    private javax.swing.JButton Contato;
    private javax.swing.JButton Home;
    private javax.swing.JLabel IdProduto1;
    private javax.swing.JLabel IdProduto2;
    private javax.swing.JLabel IdProduto3;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JLabel PARCELA1;
    private javax.swing.JLabel PARCELA2;
    private javax.swing.JLabel PARCELA3;
    private javax.swing.JLabel PRECO1;
    private javax.swing.JLabel PRECO2;
    private javax.swing.JLabel PRECO3;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JComboBox<String> Produtos2;
    private javax.swing.JComboBox<String> Produtos3;
    private javax.swing.JComboBox<String> Produtos7;
    private javax.swing.JLabel QUANTITDADE;
    private javax.swing.JLabel QUANTITDADE1;
    private javax.swing.JLabel QUANTITDADE2;
    private javax.swing.JComboBox<String> Size1;
    private javax.swing.JComboBox<String> Size2;
    private javax.swing.JComboBox<String> Size3;
    private javax.swing.JLabel TITULO1;
    private javax.swing.JLabel TITULO2;
    private javax.swing.JLabel TITULO3;
    private javax.swing.JLabel TITULO4;
    private javax.swing.JLabel TITULO5;
    private javax.swing.JLabel TITULO6;
    private javax.swing.JLabel Tamanho1;
    private javax.swing.JLabel Tamanho2;
    private javax.swing.JLabel Tamanho3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
