/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import classe.Sessao;
import classe.carrinhoBD;
import classe.itemCarrinho;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nmare
 */
public class TelaCheckoutPix extends javax.swing.JFrame {
    
    ArrayList<itemCarrinho> lista;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCheckoutPix.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaCheckoutPix() {
        initComponents();
        
        carrinhoBD banco = new carrinhoBD();

        if (Sessao.getUsuarioLogado() != null) {
            lista = banco.listarPorUsuario(
                Sessao.getUsuarioLogado().getId()
            );
        }

        
        double total = 0;
        
        
        for(itemCarrinho c : lista) {
            
            total += c.getQuantidade() * c.getPreco();
            
            
        }   
        
        TOTAL1.setText("R$ " + (total));

        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ProdutoNoCarrinho = new javax.swing.JButton();
        FinalizarCompra1 = new javax.swing.JButton();
        FinalizarCompra2 = new javax.swing.JButton();
        PixSelecionado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        FinalizarCompra = new javax.swing.JButton();
        FRETE = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        TOTAL1 = new javax.swing.JLabel();
        FRETE1 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Contato = new javax.swing.JButton();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(90, 90, 90));

        ProdutoNoCarrinho.setBackground(new java.awt.Color(102, 102, 102));
        ProdutoNoCarrinho.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ProdutoNoCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        ProdutoNoCarrinho.setText("Forma de Pagamento");
        ProdutoNoCarrinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ProdutoNoCarrinho.setContentAreaFilled(false);
        ProdutoNoCarrinho.setFocusPainted(false);
        ProdutoNoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoNoCarrinhoActionPerformed(evt);
            }
        });

        FinalizarCompra1.setBackground(new java.awt.Color(102, 102, 102));
        FinalizarCompra1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FinalizarCompra1.setForeground(new java.awt.Color(255, 255, 255));
        FinalizarCompra1.setText("Cartão de Crédito");
        FinalizarCompra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FinalizarCompra1.setContentAreaFilled(false);
        FinalizarCompra1.setFocusPainted(false);
        FinalizarCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra1ActionPerformed(evt);
            }
        });

        FinalizarCompra2.setBackground(new java.awt.Color(102, 102, 102));
        FinalizarCompra2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FinalizarCompra2.setForeground(new java.awt.Color(255, 255, 255));
        FinalizarCompra2.setText("PIX");
        FinalizarCompra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FinalizarCompra2.setContentAreaFilled(false);
        FinalizarCompra2.setFocusPainted(false);
        FinalizarCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompra2ActionPerformed(evt);
            }
        });

        PixSelecionado.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        PixSelecionado.setForeground(new java.awt.Color(255, 255, 255));
        PixSelecionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PixSelecionado.setText("Pix Selecionado.");
        PixSelecionado.setToolTipText("");
        PixSelecionado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PixSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(ProdutoNoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(FinalizarCompra2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(FinalizarCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ProdutoNoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(FinalizarCompra1)
                .addGap(78, 78, 78)
                .addComponent(FinalizarCompra2)
                .addGap(92, 92, 92)
                .addComponent(PixSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 282, -1, 420));

        jPanel4.setBackground(new java.awt.Color(90, 90, 90));

        FinalizarCompra.setBackground(new java.awt.Color(102, 102, 102));
        FinalizarCompra.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FinalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        FinalizarCompra.setText("Pagar");
        FinalizarCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FinalizarCompra.setContentAreaFilled(false);
        FinalizarCompra.setFocusPainted(false);
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });

        FRETE.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FRETE.setForeground(new java.awt.Color(255, 255, 255));
        FRETE.setText("Frete:");

        TOTAL.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        TOTAL.setForeground(new java.awt.Color(255, 255, 255));
        TOTAL.setText("Valor Final:");

        TOTAL1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        TOTAL1.setForeground(new java.awt.Color(255, 255, 255));
        TOTAL1.setText("R$");

        FRETE1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FRETE1.setForeground(new java.awt.Color(255, 255, 255));
        FRETE1.setText("Grátis");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FRETE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FRETE1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOTAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FRETE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FRETE1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TOTAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112)
                .addComponent(FinalizarCompra)
                .addGap(64, 64, 64))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 282, -1, 420));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutoNoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoNoCarrinhoActionPerformed

    }//GEN-LAST:event_ProdutoNoCarrinhoActionPerformed

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed
        // TODO add your handling code here:
        TelaPagamento screen;
        screen = new TelaPagamento();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    private void FinalizarCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompra1ActionPerformed

    private void FinalizarCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompra2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FinalizarCompra2ActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCheckoutPix().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JLabel FRETE;
    private javax.swing.JLabel FRETE1;
    private javax.swing.JButton FinalizarCompra;
    private javax.swing.JButton FinalizarCompra1;
    private javax.swing.JButton FinalizarCompra2;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JLabel PixSelecionado;
    private javax.swing.JButton ProdutoNoCarrinho;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel TOTAL1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
