/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author nmare
 */
public class TelaStaffAdicionarProd extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaStaffAdicionarProd.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaStaffAdicionarProd() {
        initComponents();
        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        Contato = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Adicionarproduto = new javax.swing.JButton();
        AddProd = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Staff = new javax.swing.JButton();
        preco = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        descricao = new javax.swing.JTextField();
        tamanho = new javax.swing.JTextField();
        precodoproduto = new javax.swing.JLabel();
        nomedoproduto = new javax.swing.JLabel();
        descdoproduto = new javax.swing.JLabel();
        tamanhodoproduto = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        qtddoproduto = new javax.swing.JLabel();
        GerenciarProdutos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Adicionarproduto.setBackground(new java.awt.Color(102, 102, 102));
        Adicionarproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Adicionarproduto.setForeground(new java.awt.Color(255, 255, 255));
        Adicionarproduto.setText("Adicionar produto");
        Adicionarproduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Adicionarproduto.setContentAreaFilled(false);
        Adicionarproduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Adicionarproduto.setFocusPainted(false);
        Adicionarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarprodutoActionPerformed(evt);
            }
        });
        jPanel1.add(Adicionarproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 320, 50));

        AddProd.setBackground(new java.awt.Color(102, 102, 102));
        AddProd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        AddProd.setForeground(new java.awt.Color(255, 255, 255));
        AddProd.setText("Adicionar produtos");
        AddProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        AddProd.setContentAreaFilled(false);
        AddProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddProd.setFocusPainted(false);
        AddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProdActionPerformed(evt);
            }
        });
        jPanel1.add(AddProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 50));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        Staff.setBackground(new java.awt.Color(102, 102, 102));
        Staff.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Staff.setForeground(new java.awt.Color(255, 255, 255));
        Staff.setText("STAFF");
        Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        jPanel1.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, -1, -1));

        preco.setBackground(new java.awt.Color(102, 102, 102));
        preco.setForeground(new java.awt.Color(255, 255, 255));
        preco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 470, 40));

        nome.setBackground(new java.awt.Color(102, 102, 102));
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 470, 40));

        descricao.setBackground(new java.awt.Color(102, 102, 102));
        descricao.setForeground(new java.awt.Color(255, 255, 255));
        descricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 470, 40));

        tamanho.setBackground(new java.awt.Color(102, 102, 102));
        tamanho.setForeground(new java.awt.Color(255, 255, 255));
        tamanho.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(tamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 470, 40));

        precodoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        precodoproduto.setForeground(new java.awt.Color(255, 255, 255));
        precodoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precodoproduto.setText("Preço do produto:");
        jPanel1.add(precodoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 170, 40));

        nomedoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        nomedoproduto.setForeground(new java.awt.Color(255, 255, 255));
        nomedoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomedoproduto.setText("Nome do produto:");
        jPanel1.add(nomedoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 170, 40));

        descdoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        descdoproduto.setForeground(new java.awt.Color(255, 255, 255));
        descdoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descdoproduto.setText("Descrição do produto:");
        jPanel1.add(descdoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 170, 40));

        tamanhodoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        tamanhodoproduto.setForeground(new java.awt.Color(255, 255, 255));
        tamanhodoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamanhodoproduto.setText("Tamanho do produto:");
        jPanel1.add(tamanhodoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 170, 40));

        quantidade.setBackground(new java.awt.Color(102, 102, 102));
        quantidade.setForeground(new java.awt.Color(255, 255, 255));
        quantidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 470, 40));

        qtddoproduto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        qtddoproduto.setForeground(new java.awt.Color(255, 255, 255));
        qtddoproduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtddoproduto.setText("Quantidade do produto:");
        jPanel1.add(qtddoproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 170, 40));

        GerenciarProdutos.setBackground(new java.awt.Color(102, 102, 102));
        GerenciarProdutos.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        GerenciarProdutos.setForeground(new java.awt.Color(255, 255, 255));
        GerenciarProdutos.setText("Gerenciar produtos");
        GerenciarProdutos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        GerenciarProdutos.setContentAreaFilled(false);
        GerenciarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GerenciarProdutos.setFocusPainted(false);
        GerenciarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(GerenciarProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 320, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        TelaCarrinho screen;
        screen = new TelaCarrinho();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void AdicionarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarprodutoActionPerformed

    
    JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso!");
    }//GEN-LAST:event_AdicionarprodutoActionPerformed

    private void AddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProdActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        // TODO add your handling code here:
            System.out.print("aaaa");
            TelaStaffInicio screen;
            screen = new TelaStaffInicio();
            screen.setVisible(true);

            this.setVisible(false);
    }//GEN-LAST:event_StaffActionPerformed

    private void GerenciarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GerenciarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaStaffAdicionarProd().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProd;
    private javax.swing.JButton Adicionarproduto;
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JButton GerenciarProdutos;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JButton Staff;
    private javax.swing.JLabel descdoproduto;
    private javax.swing.JTextField descricao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomedoproduto;
    private javax.swing.JTextField preco;
    private javax.swing.JLabel precodoproduto;
    private javax.swing.JLabel qtddoproduto;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField tamanho;
    private javax.swing.JLabel tamanhodoproduto;
    // End of variables declaration//GEN-END:variables
}
