/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/*import classe.produto;
import classe.produtoBD;
import classe.carrinho;*/
import classe.carrinhoBD;
import classe.Sessao;
import classe.itemCarrinho;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.JOptionPane;

/**
 *
 * @author nmare
 */
public class TelaCarrinho extends javax.swing.JFrame {
    
    ArrayList<itemCarrinho> lista;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCarrinho.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaCarrinho() {
        initComponents();

        carrinhoBD banco = new carrinhoBD();

        if (Sessao.getUsuarioLogado() != null) {
            lista = banco.listarPorUsuario(
                Sessao.getUsuarioLogado().getId()
            );
        }

        DefaultTableModel modelo =
                (DefaultTableModel) tabelaCarrinho.getModel();

        modelo.setRowCount(0);
        
        double total = 0;
        
        
        for(itemCarrinho c : lista) {

            modelo.addRow(new Object[]{
                c.getNome(),
                c.getTamanho(),
                c.getQuantidade(),
                c.getPreco()
            });
            
            total += c.getQuantidade() * c.getPreco();
            
        }   
        
        TOTAL1.setText("R$ " + (total));

        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas":
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calçados":
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Bermudas":
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                    break;

                case "Calças":
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    break;
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCarrinho = new javax.swing.JTable();
        removerProduto = new javax.swing.JButton();
        removerTudo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        ContinuarComprando = new javax.swing.JButton();
        FinalizarCompra = new javax.swing.JButton();
        TOTAL = new javax.swing.JLabel();
        TOTAL1 = new javax.swing.JLabel();
        FRETE = new javax.swing.JLabel();
        FRETE1 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Contato = new javax.swing.JButton();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(90, 90, 90));

        tabelaCarrinho.setBackground(new java.awt.Color(153, 153, 153));
        tabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Tamanho", "Quantidade", "Valor Unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCarrinho);

        removerProduto.setBackground(new java.awt.Color(102, 102, 102));
        removerProduto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        removerProduto.setForeground(new java.awt.Color(255, 255, 255));
        removerProduto.setText("Remover produto desejado");
        removerProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        removerProduto.setContentAreaFilled(false);
        removerProduto.setFocusPainted(false);
        removerProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProdutoActionPerformed(evt);
            }
        });

        removerTudo.setBackground(new java.awt.Color(102, 102, 102));
        removerTudo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        removerTudo.setForeground(new java.awt.Color(255, 255, 255));
        removerTudo.setText("Remover todos os produtos");
        removerTudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        removerTudo.setContentAreaFilled(false);
        removerTudo.setFocusPainted(false);
        removerTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerTudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(removerTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(removerProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removerTudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerProduto)
                .addGap(11, 11, 11))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 410));

        jPanel4.setBackground(new java.awt.Color(90, 90, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContinuarComprando.setBackground(new java.awt.Color(102, 102, 102));
        ContinuarComprando.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ContinuarComprando.setForeground(new java.awt.Color(255, 255, 255));
        ContinuarComprando.setText("Continuar Comprando");
        ContinuarComprando.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ContinuarComprando.setContentAreaFilled(false);
        ContinuarComprando.setFocusPainted(false);
        ContinuarComprando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarComprandoActionPerformed(evt);
            }
        });
        jPanel4.add(ContinuarComprando, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 208, -1));

        FinalizarCompra.setBackground(new java.awt.Color(102, 102, 102));
        FinalizarCompra.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FinalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        FinalizarCompra.setText("Pagar");
        FinalizarCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        FinalizarCompra.setContentAreaFilled(false);
        FinalizarCompra.setFocusPainted(false);
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });
        jPanel4.add(FinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 208, -1));

        TOTAL.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        TOTAL.setForeground(new java.awt.Color(255, 255, 255));
        TOTAL.setText("Valor Final:");
        jPanel4.add(TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 50));

        TOTAL1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        TOTAL1.setForeground(new java.awt.Color(255, 255, 255));
        TOTAL1.setText("R$");
        jPanel4.add(TOTAL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 50));

        FRETE.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FRETE.setForeground(new java.awt.Color(255, 255, 255));
        FRETE.setText("Frete:");
        jPanel4.add(FRETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        FRETE1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        FRETE1.setForeground(new java.awt.Color(255, 255, 255));
        FRETE1.setText("Grátis");
        jPanel4.add(FRETE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 60, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 340, 410));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed
        // TODO add your handling code here:
        TelaCheckout screen;
        screen = new TelaCheckout();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        TelaLogin screen;
        screen = new TelaLogin();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_LoginActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        new TelaCarrinho().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        TelaContato screen;
        screen = new TelaContato();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_ContatoActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void ContinuarComprandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarComprandoActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);
    }//GEN-LAST:event_ContinuarComprandoActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        TelaInicio screen;
        screen = new TelaInicio();
        screen.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void removerProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProdutoActionPerformed
        new TelaRemover().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_removerProdutoActionPerformed

    private void removerTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerTudoActionPerformed
        int idUsuario = Sessao.getUsuarioLogado().getId();

        carrinhoBD dao = new carrinhoBD();

        dao.removerTodosItens(idUsuario);

        JOptionPane.showMessageDialog(this, "Carrinho esvaziado!");

        lista = dao.listarPorUsuario(idUsuario);

        DefaultTableModel modelo = (DefaultTableModel) tabelaCarrinho.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_removerTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCarrinho().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JButton ContinuarComprando;
    private javax.swing.JLabel FRETE;
    private javax.swing.JLabel FRETE1;
    private javax.swing.JButton FinalizarCompra;
    private javax.swing.JButton Home;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel TOTAL1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerProduto;
    private javax.swing.JButton removerTudo;
    private javax.swing.JTable tabelaCarrinho;
    // End of variables declaration//GEN-END:variables
}
