/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import classe.usuario;
import classe.usuarioBD;
import classe.Sessao;
import javax.swing.JOptionPane;

/**
 *
 * @author nmare
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaInicio
     */
    public TelaLogin() {
        initComponents();

        // Listener para o JComboBox
        Produtos.addActionListener(e -> {
            String categoria = Produtos.getSelectedItem().toString();

            switch (categoria) {
                case "Camisetas" -> {
                    new TelaCamisas().setVisible(true);
                    this.setVisible(false);
                }

                case "Calçados" -> {
                    new TelaCalcados().setVisible(true);
                    this.setVisible(false);
                }

                case "Bermudas" -> {
                    new TelaBermudas().setVisible(true);
                    this.setVisible(false);
                }

                case "Calças" -> {
                    new TelaCalcas().setVisible(true);
                    this.setVisible(false);
                    // Você pode adicionar quantos quiser
                }
                // Você pode adicionar quantos quiser
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        psw = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        Incorreto = new javax.swing.JLabel();
        Staff = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Carrinho = new javax.swing.JButton();
        Contato = new javax.swing.JButton();
        Produtos = new javax.swing.JComboBox<>();
        Barrinha = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(102, 102, 102));
        login.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("FAZER LOGIN");
        login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        login.setContentAreaFilled(false);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setFocusPainted(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 343, 47));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Não tem uma conta? Crie uma aqui");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 343, 47));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite o usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 38));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Digite a senha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, 38));

        psw.setBackground(new java.awt.Color(102, 102, 102));
        psw.setForeground(new java.awt.Color(255, 255, 255));
        psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswActionPerformed(evt);
            }
        });
        jPanel1.add(psw, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 192, 38));

        user.setBackground(new java.awt.Color(102, 102, 102));
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 193, 38));

        Incorreto.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Incorreto.setForeground(new java.awt.Color(255, 255, 255));
        Incorreto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Incorreto.setText("_________________________________________________");
        Incorreto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Incorreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 343, -1));

        Staff.setBackground(new java.awt.Color(102, 102, 102));
        Staff.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Staff.setForeground(new java.awt.Color(255, 255, 255));
        Staff.setText("STAFF");
        Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });
        jPanel1.add(Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Minha Conta");
        Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Login.setContentAreaFilled(false);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setFocusPainted(false);
        Login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 70, 80, 20));

        Carrinho.setBackground(new java.awt.Color(102, 102, 102));
        Carrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTO2196.png_860-removebg-preview.png"))); // NOI18N
        Carrinho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Carrinho.setContentAreaFilled(false);
        Carrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Carrinho.setFocusPainted(false);
        Carrinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Carrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarrinhoActionPerformed(evt);
            }
        });
        jPanel1.add(Carrinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 85, 41));

        Contato.setBackground(new java.awt.Color(102, 102, 102));
        Contato.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Contato.setForeground(new java.awt.Color(255, 255, 255));
        Contato.setText("Contato");
        Contato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Contato.setContentAreaFilled(false);
        Contato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contato.setFocusPainted(false);
        Contato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContatoActionPerformed(evt);
            }
        });
        jPanel1.add(Contato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 111, 40));

        Produtos.setBackground(new java.awt.Color(102, 102, 102));
        Produtos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Produtos.setForeground(new java.awt.Color(255, 255, 255));
        Produtos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtos", "Camisetas", "Calçados", "Calças", "Bermudas" }));
        Produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(Produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 98, 41));

        javax.swing.GroupLayout BarrinhaLayout = new javax.swing.GroupLayout(Barrinha);
        Barrinha.setLayout(BarrinhaLayout);
        BarrinhaLayout.setHorizontalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        BarrinhaLayout.setVerticalGroup(
            BarrinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel1.add(Barrinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/FOTODarkStar.png"))); // NOI18N
        jPanel1.add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        Home.setBackground(new java.awt.Color(102, 102, 102));
        Home.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        Home.setContentAreaFilled(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 120, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        String username = user.getText();
        String passwords = psw.getText();

        usuarioBD usuarioBD = new classe.usuarioBD();
        usuario logado = usuarioBD.fazerLogin(username, passwords);

        if (logado != null && "staff".equals(logado.getTipo())) {
            
            Sessao.setUsuarioLogado(logado);
            new TelaStaffInicio().setVisible(true);
            this.dispose();
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos para ter acesso staff.");
            
        }
    }//GEN-LAST:event_StaffActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new TelaRegistro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String username = user.getText();
        String passwords = psw.getText();

        usuarioBD usuarioBD = new classe.usuarioBD();
        usuario logado = usuarioBD.fazerLogin(username, passwords);

        if (logado != null) {
            
            Sessao.setUsuarioLogado(logado);
            new TelaInicio().setVisible(true);
            this.dispose();
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos.");
        
        }
    }//GEN-LAST:event_loginActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    private void CarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarrinhoActionPerformed
        // TODO add your handling code here:
        new TelaCarrinho().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CarrinhoActionPerformed

    private void ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContatoActionPerformed
        // TODO add your handling code here:
        new TelaContato().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ContatoActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdutosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        new TelaInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barrinha;
    private javax.swing.JButton Carrinho;
    private javax.swing.JButton Contato;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Incorreto;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton Login;
    private javax.swing.JComboBox<String> Produtos;
    private javax.swing.JButton Staff;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField psw;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
